### PR TITLE
Refactor/reuse jumper

### PR DESCRIPTION
**Pull request by rharriso**
@renstrom Here's the work I've got so far.

* I've added much larger strings for testing, both matching near the beginning and end of the string.
* Originally I wanted to keep the interaction between match and match rank, basically making a match a test of rankmatch > 0. However this led to unnecessary overhead in some cases. I ended up modifying the match code for use in RankMatch, so that it only performs a subset of the Levenstein distance.
* I also tried other methods of iterating over the Rune arrays, but it seem as though you may found the most efficient with the continue jump.

Here are the results of the benchmarks.

```
➜  fuzzy git:(master) ✗ go test -bench .     
PASS
BenchmarkMatch  50000000                66.7 ns/op
BenchmarkMatchBigLate     500000              6839 ns/op
BenchmarkMatchBigEarly  50000000                52.0 ns/op
BenchmarkRankMatch       5000000               490 ns/op
BenchmarkRankMatchBigLate          50000             48767 ns/op
BenchmarkRankMatchBigEarly         50000             37500 ns/op
BenchmarkLevenshteinDistance     5000000               374 ns/op
BenchmarkLevenshteinDistanceBigLate        50000             41915 ns/op
BenchmarkLevenshteinDistanceBigEarly       50000             37561 ns/op
```
```
➜  fuzzy git:(refactor/reuse-jumper) go test -bench .
PASS
BenchmarkMatch  50000000                65.6 ns/op
BenchmarkMatchBigLate     500000              6775 ns/op
BenchmarkMatchBigEarly  50000000                51.6 ns/op
BenchmarkRankMatch      50000000                67.8 ns/op
BenchmarkRankMatchBigLate         500000              7045 ns/op
BenchmarkRankMatchBigEarly        500000              4442 ns/op
BenchmarkLevenshteinDistance     5000000               367 ns/op
BenchmarkLevenshteinDistanceBigLate        50000             41962 ns/op
BenchmarkLevenshteinDistanceBigEarly       50000             37641 ns/op
```

You can see that the refactor/reuse-jumper branch performs much better in the BigRankMatch benchmarks (~10x in this test). The growth rate looks like O(n) for the refactor branch and O(n^2), I have benchmarked a growth rate yet, but just by looking at Levenstein vs. RankMatch, thats what I would guess.

Sorry about the long message

Regards,
Ross

### CODE REVIEW

**Comment by renstrom** [comment]
Nice speedup on `RankMatch` for long strings! I'm gonna try and review this weekend hopefully, but just some minor nitpicks to start with:

Don't export the `DeBelloGallico` constant, I'm not sure it warrants its own file either (move it into one of the other test files). And remove the `gitignore` since it only contains editor stuff which are better kept in your global gitignore.

**Comment by rharriso** [comment]
Can do .... Actually it's only in its own file because vim was chugging on
it until I split the lines. Will update when I can.

**Comment by renstrom** [comment]
I see. Try something like `set synmaxcol=400` in Vim. It should help speed up on files with very long lines.

>Maximum column in which to search for syntax items.  In long lines the text after this column is not highlighted and following lines may not be highlighted correctly, because the syntax state is cleared. This helps to avoid very slow redrawing for an XML file that is one long line. Set to zero to remove the limit.

**Comment by rharriso** [comment]
I'll check that out thanks for the tips!

**Comment by renstrom** [comment]
@rharriso Is this done now? Or do you have more tweaks incoming? Otherwise I'll merge it.

**Comment by rharriso** [comment]
It's done if you don't have any more feedback.

**Comment by renstrom** [comment]
Not really. Thanks! :)

**Pull request merged**
